### ISSUE TITLE
Can't seem to get this to work...

### ISSUE THREAD

**Issue by swablueme** [billyvg/pokemon-go-iv#2]
<img src=http://i.imgur.com/1BHw8Cs.png>
I can't seem to find the module as shown in the image.

npm version: 3.10.5
node version: v6.3.1
Running on Windows 10

**Comment by billyvg** [comment]
In your `git\pokemon-go-iv`directory run `node bin\app.js` instead of `node pokemon-go-iv`

If you install the package globally (i.e.`npm install -g pokemon-go-iv`) then, if your PATH is setup correctly, you will be able to run `pokemon-go-iv` from anywhere (without calling `node` before it)

**Comment by Nicte** [comment]
Hey, don't want to create an issue, just wanted to thank you. This is the simplest tool (and by far the easiest one) to get exact IV's. Nothing complex, just gets the job done!

Did you create it as part of a bigger project or something?

**Comment by billyvg** [comment]
Yep, I started off with this and wasn't satisfied :)

**Comment by swablueme** [comment]
Thanks mate :+1:
