### ISSUE TITLE
Usage - could you explain parameters -l and -s?

### ISSUE THREAD

**Issue by aisbergde** [billyvg/pokemon-go-iv#6]
the usage should be:
node pokemon-go-iv -u <username> -p <password> -a <"ptc"|"google"> -l "<location>" [-s time|iv] [--cache]
but I have no idea what the -l and -s should do, especially what location to enter.
other parameters are clear for me, but may be there could also a description for other users.

Currently I am not able to install ar run the program so I can't test what this could mean.

**Comment by enriquemh** [comment]
-l is the location value; What I have done is to use google maps, select a location where you are and copy the value in the url:For this url https://www.google.dk/maps/@38.8934065,-77.0384208,14.79z 
use -l "38.8934065,-77.0384208".
-s is for sorting the data when returning, sorted by time acquired (time) or by iv (iv).

If you have problems in windows running the script, try to go into the nodejs/node-modules/npm folder and run: npm install node-gyp@latest, cause there is some problem with the node-gyp installed inside the npm tool. And remember to install the visual c tools so it rebuilds correctly.

**Comment by billyvg** [comment]
location is now removed (24974bd4ab168c8e78dc31898d4c4fe3222387e4)
and new sort values have been added (b6ca3ef472bfe4dfce4587fa3a17252d923972e4)
