### ISSUE TITLE
Location should be removed

### ISSUE THREAD

**Issue by octave-ati** [billyvg/pokemon-go-iv#8]
Why is there a location option that is required?
This could lead to an account ban if the location is wrongly entered..

Isn't it possible to remove the location all together as if logging in in "no gps" mode while still retrieving the data?

**Comment by billyvg** [comment]
Yes this is on my TODO, I will have to check to see if the APIs can be called without the location.

**Comment by octave-ati** [comment]
I've seen this on another repo and it seemed to work, which is logical because you can sort through your pokemons even without gps signal on the app

**Comment by billyvg** [comment]
Fixed in 24974bd4ab168c8e78dc31898d4c4fe3222387e4

**Comment by octave-ati** [comment]
Thanks
