### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by bwebs** [billyvg/pokemon-go-iv#9]
Getting an error on these last commits. v1.1.1 worked fine for me. Tried removing and installing again. See error below

> /usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:321
>           throw new Error("Couldn't find preset " + (0, _stringify2.default)(val) + " relative to directory " + (0, _stringify2.default)(dirname));
>           ^
> 
> Error: Couldn't find preset "es2015" relative to directory "/usr/local/lib/node_modules/pokemon-go-iv"
>     at /usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:321:17
>     at Array.map (native)
>     at OptionManager.resolvePresets (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
>     at OptionManager.mergePresets (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
>     at OptionManager.mergeOptions (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
>     at OptionManager.init (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
>     at compile (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-register/lib/node.js:103:45)
>     at loader (/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-register/lib/node.js:148:14)
>     at Object.require.extensions.(anonymous function) [as .js](/usr/local/lib/node_modules/pokemon-go-iv/node_modules/babel-register/lib/node.js:158:7)
>     at Module.load (module.js:458:32)

**Comment by billyvg** [comment]
Try pulling repo, `npm install` and try again (c1f2a6927ef3bd80c0aaf833b8fb13effed78ee0)
